//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else
// Classes
#ifndef NIDeviceInfo
#define NIDeviceInfo __NIMBUS_NAMESPACE_PREFIX_##NIDeviceInfo
#endif
#ifndef NILinkedList
#define NILinkedList __NIMBUS_NAMESPACE_PREFIX_##NILinkedList
#endif
#ifndef NIOverview
#define NIOverview __NIMBUS_NAMESPACE_PREFIX_##NIOverview
#endif
#ifndef NIOverviewConsoleLogEntry
#define NIOverviewConsoleLogEntry __NIMBUS_NAMESPACE_PREFIX_##NIOverviewConsoleLogEntry
#endif
#ifndef NIOverviewConsoleLogPageView
#define NIOverviewConsoleLogPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewConsoleLogPageView
#endif
#ifndef NIOverviewDeviceLogEntry
#define NIOverviewDeviceLogEntry __NIMBUS_NAMESPACE_PREFIX_##NIOverviewDeviceLogEntry
#endif
#ifndef NIOverviewDiskPageView
#define NIOverviewDiskPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewDiskPageView
#endif
#ifndef NIOverviewEventLogEntry
#define NIOverviewEventLogEntry __NIMBUS_NAMESPACE_PREFIX_##NIOverviewEventLogEntry
#endif
#ifndef NIOverviewGraphPageView
#define NIOverviewGraphPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewGraphPageView
#endif
#ifndef NIOverviewGraphView
#define NIOverviewGraphView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewGraphView
#endif
#ifndef NIOverviewLogEntry
#define NIOverviewLogEntry __NIMBUS_NAMESPACE_PREFIX_##NIOverviewLogEntry
#endif
#ifndef NIOverviewLogger
#define NIOverviewLogger __NIMBUS_NAMESPACE_PREFIX_##NIOverviewLogger
#endif
#ifndef NIOverviewMaxLogLevelPageView
#define NIOverviewMaxLogLevelPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewMaxLogLevelPageView
#endif
#ifndef NIOverviewMemoryPageView
#define NIOverviewMemoryPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewMemoryPageView
#endif
#ifndef NIOverviewPageView
#define NIOverviewPageView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewPageView
#endif
#ifndef NIOverviewView
#define NIOverviewView __NIMBUS_NAMESPACE_PREFIX_##NIOverviewView
#endif
// Functions
#ifndef NIOverviewLogMethod
#define NIOverviewLogMethod __NIMBUS_NAMESPACE_PREFIX_##NIOverviewLogMethod
#endif
#ifndef NIOverviewStatusBarHeight
#define NIOverviewStatusBarHeight __NIMBUS_NAMESPACE_PREFIX_##NIOverviewStatusBarHeight
#endif
#ifndef NIStringFromBytes
#define NIStringFromBytes __NIMBUS_NAMESPACE_PREFIX_##NIStringFromBytes
#endif
#ifndef NIOverviewSwizzleMethods
#define NIOverviewSwizzleMethods __NIMBUS_NAMESPACE_PREFIX_##NIOverviewSwizzleMethods
#endif
// Externs
#ifndef NIOverviewLoggerDidAddConsoleLog
#define NIOverviewLoggerDidAddConsoleLog __NIMBUS_NAMESPACE_PREFIX_##NIOverviewLoggerDidAddConsoleLog
#endif
#endif
