//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else

#ifndef __NIMBUS_NS_SYMBOL
// We need to have multiple levels of macros here so that __NIMBUS_NAMESPACE_PREFIX_ is
// properly replaced by the time we concatenate the namespace prefix.
#define __NIMBUS_NS_REWRITE(ns, symbol) ns ## _ ## symbol
#define __NIMBUS_NS_BRIDGE(ns, symbol) __NIMBUS_NS_REWRITE(ns, symbol)
#define __NIMBUS_NS_SYMBOL(symbol) __NIMBUS_NS_BRIDGE(__NIMBUS_NAMESPACE_PREFIX_, symbol)
#endif

// Classes
#ifndef NICellFactory
#define NICellFactory __NIMBUS_NS_SYMBOL(NICellFactory)
#endif
#ifndef NIDeviceInfo
#define NIDeviceInfo __NIMBUS_NS_SYMBOL(NIDeviceInfo)
#endif
#ifndef NIImageMemoryCache
#define NIImageMemoryCache __NIMBUS_NS_SYMBOL(NIImageMemoryCache)
#endif
#ifndef NILinkedList
#define NILinkedList __NIMBUS_NS_SYMBOL(NILinkedList)
#endif
#ifndef NIOverview
#define NIOverview __NIMBUS_NS_SYMBOL(NIOverview)
#endif
#ifndef NIOverviewConsoleLogEntry
#define NIOverviewConsoleLogEntry __NIMBUS_NS_SYMBOL(NIOverviewConsoleLogEntry)
#endif
#ifndef NIOverviewConsoleLogPageView
#define NIOverviewConsoleLogPageView __NIMBUS_NS_SYMBOL(NIOverviewConsoleLogPageView)
#endif
#ifndef NIOverviewDeviceLogEntry
#define NIOverviewDeviceLogEntry __NIMBUS_NS_SYMBOL(NIOverviewDeviceLogEntry)
#endif
#ifndef NIOverviewDiskPageView
#define NIOverviewDiskPageView __NIMBUS_NS_SYMBOL(NIOverviewDiskPageView)
#endif
#ifndef NIOverviewEventLogEntry
#define NIOverviewEventLogEntry __NIMBUS_NS_SYMBOL(NIOverviewEventLogEntry)
#endif
#ifndef NIOverviewGraphPageView
#define NIOverviewGraphPageView __NIMBUS_NS_SYMBOL(NIOverviewGraphPageView)
#endif
#ifndef NIOverviewGraphView
#define NIOverviewGraphView __NIMBUS_NS_SYMBOL(NIOverviewGraphView)
#endif
#ifndef NIOverviewImageMemoryCacheEntry
#define NIOverviewImageMemoryCacheEntry __NIMBUS_NS_SYMBOL(NIOverviewImageMemoryCacheEntry)
#endif
#ifndef NIOverviewLogEntry
#define NIOverviewLogEntry __NIMBUS_NS_SYMBOL(NIOverviewLogEntry)
#endif
#ifndef NIOverviewLogger
#define NIOverviewLogger __NIMBUS_NS_SYMBOL(NIOverviewLogger)
#endif
#ifndef NIOverviewMaxLogLevelPageView
#define NIOverviewMaxLogLevelPageView __NIMBUS_NS_SYMBOL(NIOverviewMaxLogLevelPageView)
#endif
#ifndef NIOverviewMemoryCacheController
#define NIOverviewMemoryCacheController __NIMBUS_NS_SYMBOL(NIOverviewMemoryCacheController)
#endif
#ifndef NIOverviewMemoryCacheEntry
#define NIOverviewMemoryCacheEntry __NIMBUS_NS_SYMBOL(NIOverviewMemoryCacheEntry)
#endif
#ifndef NIOverviewMemoryCachePageView
#define NIOverviewMemoryCachePageView __NIMBUS_NS_SYMBOL(NIOverviewMemoryCachePageView)
#endif
#ifndef NIOverviewMemoryPageView
#define NIOverviewMemoryPageView __NIMBUS_NS_SYMBOL(NIOverviewMemoryPageView)
#endif
#ifndef NIOverviewPageView
#define NIOverviewPageView __NIMBUS_NS_SYMBOL(NIOverviewPageView)
#endif
#ifndef NIOverviewView
#define NIOverviewView __NIMBUS_NS_SYMBOL(NIOverviewView)
#endif
#ifndef NISubtitleCellObject
#define NISubtitleCellObject __NIMBUS_NS_SYMBOL(NISubtitleCellObject)
#endif
#ifndef NITableViewModel
#define NITableViewModel __NIMBUS_NS_SYMBOL(NITableViewModel)
#endif
#ifndef NITableViewModelFooter
#define NITableViewModelFooter __NIMBUS_NS_SYMBOL(NITableViewModelFooter)
#endif
#ifndef NITitleCellObject
#define NITitleCellObject __NIMBUS_NS_SYMBOL(NITitleCellObject)
#endif
#ifndef Nimbus
#define Nimbus __NIMBUS_NS_SYMBOL(Nimbus)
#endif
// Functions
#ifndef NIOverviewLogMethod
#define NIOverviewLogMethod __NIMBUS_NS_SYMBOL(NIOverviewLogMethod)
#endif
#ifndef NIOverviewStatusBarHeight
#define NIOverviewStatusBarHeight __NIMBUS_NS_SYMBOL(NIOverviewStatusBarHeight)
#endif
#ifndef NIStringFromBytes
#define NIStringFromBytes __NIMBUS_NS_SYMBOL(NIStringFromBytes)
#endif
#ifndef NIOverviewSwizzleMethods
#define NIOverviewSwizzleMethods __NIMBUS_NS_SYMBOL(NIOverviewSwizzleMethods)
#endif
// Externs
#ifndef NIOverviewLoggerDidAddConsoleLog
#define NIOverviewLoggerDidAddConsoleLog __NIMBUS_NS_SYMBOL(NIOverviewLoggerDidAddConsoleLog)
#endif
#endif
