//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else
// Classes
#ifndef NICSSParser
#define NICSSParser __NIMBUS_NAMESPACE_PREFIX_##NICSSParser
#endif
#ifndef NICSSRuleset
#define NICSSRuleset __NIMBUS_NAMESPACE_PREFIX_##NICSSRuleset
#endif
#ifndef NIChameleonObserver
#define NIChameleonObserver __NIMBUS_NAMESPACE_PREFIX_##NIChameleonObserver
#endif
#ifndef NIDOM
#define NIDOM __NIMBUS_NAMESPACE_PREFIX_##NIDOM
#endif
#ifndef NILinkedList
#define NILinkedList __NIMBUS_NAMESPACE_PREFIX_##NILinkedList
#endif
#ifndef NINetworkRequestOperation
#define NINetworkRequestOperation __NIMBUS_NAMESPACE_PREFIX_##NINetworkRequestOperation
#endif
#ifndef NIStylesheet
#define NIStylesheet __NIMBUS_NAMESPACE_PREFIX_##NIStylesheet
#endif
#ifndef NIStylesheetCache
#define NIStylesheetCache __NIMBUS_NAMESPACE_PREFIX_##NIStylesheetCache
#endif
#ifndef NI_FIX_CATEGORY_BUG_UIButton_NIStyleable
#define NI_FIX_CATEGORY_BUG_UIButton_NIStyleable __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_UIButton_NIStyleable
#endif
#ifndef NI_FIX_CATEGORY_BUG_UILabel_NIStyleable
#define NI_FIX_CATEGORY_BUG_UILabel_NIStyleable __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_UILabel_NIStyleable
#endif
#ifndef NI_FIX_CATEGORY_BUG_UINavigationBar_NIStyleable
#define NI_FIX_CATEGORY_BUG_UINavigationBar_NIStyleable __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_UINavigationBar_NIStyleable
#endif
#ifndef NI_FIX_CATEGORY_BUG_UIView_NIStyleable
#define NI_FIX_CATEGORY_BUG_UIView_NIStyleable __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_UIView_NIStyleable
#endif
// Functions
#ifndef cssConsume
#define cssConsume __NIMBUS_NAMESPACE_PREFIX_##cssConsume
#endif
#ifndef csslex
#define csslex __NIMBUS_NAMESPACE_PREFIX_##csslex
#endif
#ifndef css_create_buffer
#define css_create_buffer __NIMBUS_NAMESPACE_PREFIX_##css_create_buffer
#endif
#ifndef csswrap
#define csswrap __NIMBUS_NAMESPACE_PREFIX_##csswrap
#endif
#ifndef cssrestart
#define cssrestart __NIMBUS_NAMESPACE_PREFIX_##cssrestart
#endif
#ifndef css_switch_to_buffer
#define css_switch_to_buffer __NIMBUS_NAMESPACE_PREFIX_##css_switch_to_buffer
#endif
#ifndef cssalloc
#define cssalloc __NIMBUS_NAMESPACE_PREFIX_##cssalloc
#endif
#ifndef css_delete_buffer
#define css_delete_buffer __NIMBUS_NAMESPACE_PREFIX_##css_delete_buffer
#endif
#ifndef cssfree
#define cssfree __NIMBUS_NAMESPACE_PREFIX_##cssfree
#endif
#ifndef css_flush_buffer
#define css_flush_buffer __NIMBUS_NAMESPACE_PREFIX_##css_flush_buffer
#endif
#ifndef csspush_buffer_state
#define csspush_buffer_state __NIMBUS_NAMESPACE_PREFIX_##csspush_buffer_state
#endif
#ifndef csspop_buffer_state
#define csspop_buffer_state __NIMBUS_NAMESPACE_PREFIX_##csspop_buffer_state
#endif
#ifndef css_scan_buffer
#define css_scan_buffer __NIMBUS_NAMESPACE_PREFIX_##css_scan_buffer
#endif
#ifndef css_scan_string
#define css_scan_string __NIMBUS_NAMESPACE_PREFIX_##css_scan_string
#endif
#ifndef css_scan_bytes
#define css_scan_bytes __NIMBUS_NAMESPACE_PREFIX_##css_scan_bytes
#endif
#ifndef cssget_lineno
#define cssget_lineno __NIMBUS_NAMESPACE_PREFIX_##cssget_lineno
#endif
#ifndef cssget_in
#define cssget_in __NIMBUS_NAMESPACE_PREFIX_##cssget_in
#endif
#ifndef cssget_out
#define cssget_out __NIMBUS_NAMESPACE_PREFIX_##cssget_out
#endif
#ifndef cssget_leng
#define cssget_leng __NIMBUS_NAMESPACE_PREFIX_##cssget_leng
#endif
#ifndef cssget_text
#define cssget_text __NIMBUS_NAMESPACE_PREFIX_##cssget_text
#endif
#ifndef cssset_lineno
#define cssset_lineno __NIMBUS_NAMESPACE_PREFIX_##cssset_lineno
#endif
#ifndef cssset_in
#define cssset_in __NIMBUS_NAMESPACE_PREFIX_##cssset_in
#endif
#ifndef cssset_out
#define cssset_out __NIMBUS_NAMESPACE_PREFIX_##cssset_out
#endif
#ifndef cssget_debug
#define cssget_debug __NIMBUS_NAMESPACE_PREFIX_##cssget_debug
#endif
#ifndef cssset_debug
#define cssset_debug __NIMBUS_NAMESPACE_PREFIX_##cssset_debug
#endif
#ifndef csslex_destroy
#define csslex_destroy __NIMBUS_NAMESPACE_PREFIX_##csslex_destroy
#endif
#ifndef cssrealloc
#define cssrealloc __NIMBUS_NAMESPACE_PREFIX_##cssrealloc
#endif
// Externs
#ifndef cssnames
#define cssnames __NIMBUS_NAMESPACE_PREFIX_##cssnames
#endif
#ifndef csslineno
#define csslineno __NIMBUS_NAMESPACE_PREFIX_##csslineno
#endif
#endif
