#!/bin/bash
#
# Build a CSS grammar for Nimbus using flex.
# http://flex.sourceforge.net/
#
# Written by Jeff Verkoeyen for the Nimbus project.
# http://jverkoey.github.com/nimbus/

flex --prefix=css --nounput css.grammar

cat CSSTokenizerPrefix lex.css.c CSSTokenizerSuffix > CSSTokenizer.m

rm lex.css.c

mv CSSTokenizer.m ../src/CSSTokenizer.m
cp CSSTokens.cpp ../src/CSSTokens.m
cp CSSTokens.h ../src/CSSTokens.h
