//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else
// Classes
#ifndef NIButtonFormElement
#define NIButtonFormElement __NIMBUS_NAMESPACE_PREFIX_##NIButtonFormElement
#endif
#ifndef NIButtonFormElementCell
#define NIButtonFormElementCell __NIMBUS_NAMESPACE_PREFIX_##NIButtonFormElementCell
#endif
#ifndef NICellFactory
#define NICellFactory __NIMBUS_NAMESPACE_PREFIX_##NICellFactory
#endif
#ifndef NICellObject
#define NICellObject __NIMBUS_NAMESPACE_PREFIX_##NICellObject
#endif
#ifndef NIFormElement
#define NIFormElement __NIMBUS_NAMESPACE_PREFIX_##NIFormElement
#endif
#ifndef NIFormElementCell
#define NIFormElementCell __NIMBUS_NAMESPACE_PREFIX_##NIFormElementCell
#endif
#ifndef NISwitchFormElement
#define NISwitchFormElement __NIMBUS_NAMESPACE_PREFIX_##NISwitchFormElement
#endif
#ifndef NISwitchFormElementCell
#define NISwitchFormElementCell __NIMBUS_NAMESPACE_PREFIX_##NISwitchFormElementCell
#endif
#ifndef NITableViewModel
#define NITableViewModel __NIMBUS_NAMESPACE_PREFIX_##NITableViewModel
#endif
#ifndef NITableViewModelFooter
#define NITableViewModelFooter __NIMBUS_NAMESPACE_PREFIX_##NITableViewModelFooter
#endif
#ifndef NITableViewModelSection
#define NITableViewModelSection __NIMBUS_NAMESPACE_PREFIX_##NITableViewModelSection
#endif
#ifndef NITextInputFormElement
#define NITextInputFormElement __NIMBUS_NAMESPACE_PREFIX_##NITextInputFormElement
#endif
#ifndef NITextInputFormElementCell
#define NITextInputFormElementCell __NIMBUS_NAMESPACE_PREFIX_##NITextInputFormElementCell
#endif
// Functions
// Externs
#endif
