//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else
// Classes
#ifndef NICenteringScrollView
#define NICenteringScrollView __NIMBUS_NAMESPACE_PREFIX_##NICenteringScrollView
#endif
#ifndef NINavigationAppearance
#define NINavigationAppearance __NIMBUS_NAMESPACE_PREFIX_##NINavigationAppearance
#endif
#ifndef NIPagingScrollView
#define NIPagingScrollView __NIMBUS_NAMESPACE_PREFIX_##NIPagingScrollView
#endif
#ifndef NIPhotoAlbumScrollView
#define NIPhotoAlbumScrollView __NIMBUS_NAMESPACE_PREFIX_##NIPhotoAlbumScrollView
#endif
#ifndef NIPhotoScrollView
#define NIPhotoScrollView __NIMBUS_NAMESPACE_PREFIX_##NIPhotoScrollView
#endif
#ifndef NIPhotoScrubberView
#define NIPhotoScrubberView __NIMBUS_NAMESPACE_PREFIX_##NIPhotoScrubberView
#endif
#ifndef NIToolbarPhotoViewController
#define NIToolbarPhotoViewController __NIMBUS_NAMESPACE_PREFIX_##NIToolbarPhotoViewController
#endif
// Functions
// Externs
#endif
