//
// Copyright 2011 Jeff Verkoeyen
// This file has been automatically generated by Nimbus' namespacing script.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef __NIMBUS_NAMESPACE_PREFIX_
#error You must define __NIMBUS_NAMESPACE_PREFIX_ in your project settings in order to use a Nimbus namespace.
#else
// Classes
#ifndef NIImageMemoryCache
#define NIImageMemoryCache __NIMBUS_NAMESPACE_PREFIX_##NIImageMemoryCache
#endif
#ifndef NILinkedList
#define NILinkedList __NIMBUS_NAMESPACE_PREFIX_##NILinkedList
#endif
#ifndef NILinkedListEnumerator
#define NILinkedListEnumerator __NIMBUS_NAMESPACE_PREFIX_##NILinkedListEnumerator
#endif
#ifndef NILinkedListLocation
#define NILinkedListLocation __NIMBUS_NAMESPACE_PREFIX_##NILinkedListLocation
#endif
#ifndef NILinkedListNode
#define NILinkedListNode __NIMBUS_NAMESPACE_PREFIX_##NILinkedListNode
#endif
#ifndef NIMemoryCache
#define NIMemoryCache __NIMBUS_NAMESPACE_PREFIX_##NIMemoryCache
#endif
#ifndef NIMemoryCacheInfo
#define NIMemoryCacheInfo __NIMBUS_NAMESPACE_PREFIX_##NIMemoryCacheInfo
#endif
#ifndef NINavigationAppearance
#define NINavigationAppearance __NIMBUS_NAMESPACE_PREFIX_##NINavigationAppearance
#endif
#ifndef NINavigationAppearanceSnapshot
#define NINavigationAppearanceSnapshot __NIMBUS_NAMESPACE_PREFIX_##NINavigationAppearanceSnapshot
#endif
#ifndef NINetworkRequestOperation
#define NINetworkRequestOperation __NIMBUS_NAMESPACE_PREFIX_##NINetworkRequestOperation
#endif
#ifndef NIOperation
#define NIOperation __NIMBUS_NAMESPACE_PREFIX_##NIOperation
#endif
#ifndef NIViewRecycler
#define NIViewRecycler __NIMBUS_NAMESPACE_PREFIX_##NIViewRecycler
#endif
#ifndef NI_FIX_CATEGORY_BUG_NSDataNimbusCore
#define NI_FIX_CATEGORY_BUG_NSDataNimbusCore __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_NSDataNimbusCore
#endif
#ifndef NI_FIX_CATEGORY_BUG_NSStringNimbusCore
#define NI_FIX_CATEGORY_BUG_NSStringNimbusCore __NIMBUS_NAMESPACE_PREFIX_##NI_FIX_CATEGORY_BUG_NSStringNimbusCore
#endif
#ifndef Nimbus
#define Nimbus __NIMBUS_NAMESPACE_PREFIX_##Nimbus
#endif
// Functions
#ifndef NICreateNonRetainingMutableArray
#define NICreateNonRetainingMutableArray __NIMBUS_NAMESPACE_PREFIX_##NICreateNonRetainingMutableArray
#endif
#ifndef NIIsArrayWithObjects
#define NIIsArrayWithObjects __NIMBUS_NAMESPACE_PREFIX_##NIIsArrayWithObjects
#endif
#ifndef NIIsInDebugger
#define NIIsInDebugger __NIMBUS_NAMESPACE_PREFIX_##NIIsInDebugger
#endif
#ifndef NIIsPad
#define NIIsPad __NIMBUS_NAMESPACE_PREFIX_##NIIsPad
#endif
#ifndef NIIsSupportedOrientation
#define NIIsSupportedOrientation __NIMBUS_NAMESPACE_PREFIX_##NIIsSupportedOrientation
#endif
#ifndef NINetworkActivityTaskDidStart
#define NINetworkActivityTaskDidStart __NIMBUS_NAMESPACE_PREFIX_##NINetworkActivityTaskDidStart
#endif
#ifndef NIPathForBundleResource
#define NIPathForBundleResource __NIMBUS_NAMESPACE_PREFIX_##NIPathForBundleResource
#endif
#ifndef NIRectContract
#define NIRectContract __NIMBUS_NAMESPACE_PREFIX_##NIRectContract
#endif
#ifndef NISwapInstanceMethods
#define NISwapInstanceMethods __NIMBUS_NAMESPACE_PREFIX_##NISwapInstanceMethods
#endif
#ifndef NIToolbarHeightForOrientation
#define NIToolbarHeightForOrientation __NIMBUS_NAMESPACE_PREFIX_##NIToolbarHeightForOrientation
#endif
#ifndef NICreateNonRetainingMutableDictionary
#define NICreateNonRetainingMutableDictionary __NIMBUS_NAMESPACE_PREFIX_##NICreateNonRetainingMutableDictionary
#endif
#ifndef NISwapClassMethods
#define NISwapClassMethods __NIMBUS_NAMESPACE_PREFIX_##NISwapClassMethods
#endif
#ifndef NICreateNonRetainingMutableSet
#define NICreateNonRetainingMutableSet __NIMBUS_NAMESPACE_PREFIX_##NICreateNonRetainingMutableSet
#endif
#ifndef NIInterfaceOrientation
#define NIInterfaceOrientation __NIMBUS_NAMESPACE_PREFIX_##NIInterfaceOrientation
#endif
#ifndef NIStatusBarAnimationCurve
#define NIStatusBarAnimationCurve __NIMBUS_NAMESPACE_PREFIX_##NIStatusBarAnimationCurve
#endif
#ifndef NIStatusBarAnimationDuration
#define NIStatusBarAnimationDuration __NIMBUS_NAMESPACE_PREFIX_##NIStatusBarAnimationDuration
#endif
#ifndef NIStatusBarBoundsChangeAnimationCurve
#define NIStatusBarBoundsChangeAnimationCurve __NIMBUS_NAMESPACE_PREFIX_##NIStatusBarBoundsChangeAnimationCurve
#endif
#ifndef NIStatusBarBoundsChangeAnimationDuration
#define NIStatusBarBoundsChangeAnimationDuration __NIMBUS_NAMESPACE_PREFIX_##NIStatusBarBoundsChangeAnimationDuration
#endif
#ifndef NINetworkActivityTaskDidFinish
#define NINetworkActivityTaskDidFinish __NIMBUS_NAMESPACE_PREFIX_##NINetworkActivityTaskDidFinish
#endif
#ifndef NIIsSetWithObjects
#define NIIsSetWithObjects __NIMBUS_NAMESPACE_PREFIX_##NIIsSetWithObjects
#endif
#ifndef NIRectShift
#define NIRectShift __NIMBUS_NAMESPACE_PREFIX_##NIRectShift
#endif
#ifndef NIStatusBarHeight
#define NIStatusBarHeight __NIMBUS_NAMESPACE_PREFIX_##NIStatusBarHeight
#endif
#ifndef NIDeviceOSVersionIsAtLeast
#define NIDeviceOSVersionIsAtLeast __NIMBUS_NAMESPACE_PREFIX_##NIDeviceOSVersionIsAtLeast
#endif
#ifndef NIPathForDocumentsResource
#define NIPathForDocumentsResource __NIMBUS_NAMESPACE_PREFIX_##NIPathForDocumentsResource
#endif
#ifndef NIRotateTransformForOrientation
#define NIRotateTransformForOrientation __NIMBUS_NAMESPACE_PREFIX_##NIRotateTransformForOrientation
#endif
#ifndef NIScreenScale
#define NIScreenScale __NIMBUS_NAMESPACE_PREFIX_##NIScreenScale
#endif
#ifndef NIRectInset
#define NIRectInset __NIMBUS_NAMESPACE_PREFIX_##NIRectInset
#endif
#ifndef NIIsStringWithAnyText
#define NIIsStringWithAnyText __NIMBUS_NAMESPACE_PREFIX_##NIIsStringWithAnyText
#endif
#ifndef NIDeviceRotationDuration
#define NIDeviceRotationDuration __NIMBUS_NAMESPACE_PREFIX_##NIDeviceRotationDuration
#endif
#ifndef NICellContentPadding
#define NICellContentPadding __NIMBUS_NAMESPACE_PREFIX_##NICellContentPadding
#endif
#ifndef NIPathForCachesResource
#define NIPathForCachesResource __NIMBUS_NAMESPACE_PREFIX_##NIPathForCachesResource
#endif
#ifndef NIUIPopoverControllerClass
#define NIUIPopoverControllerClass __NIMBUS_NAMESPACE_PREFIX_##NIUIPopoverControllerClass
#endif
#ifndef NIMakeNSRangeFromCFRange
#define NIMakeNSRangeFromCFRange __NIMBUS_NAMESPACE_PREFIX_##NIMakeNSRangeFromCFRange
#endif
#ifndef NIUITapGestureRecognizerClass
#define NIUITapGestureRecognizerClass __NIMBUS_NAMESPACE_PREFIX_##NIUITapGestureRecognizerClass
#endif
#ifndef boundf
#define boundf __NIMBUS_NAMESPACE_PREFIX_##boundf
#endif
#ifndef NISwizzleMethodsForNetworkActivityDebugging
#define NISwizzleMethodsForNetworkActivityDebugging __NIMBUS_NAMESPACE_PREFIX_##NISwizzleMethodsForNetworkActivityDebugging
#endif
#ifndef NIEnableNetworkActivityDebugging
#define NIEnableNetworkActivityDebugging __NIMBUS_NAMESPACE_PREFIX_##NIEnableNetworkActivityDebugging
#endif
#ifndef boundi
#define boundi __NIMBUS_NAMESPACE_PREFIX_##boundi
#endif
#ifndef NIDisableNetworkActivityDebugging
#define NIDisableNetworkActivityDebugging __NIMBUS_NAMESPACE_PREFIX_##NIDisableNetworkActivityDebugging
#endif
// Externs
#ifndef NIMaxLogLevel
#define NIMaxLogLevel __NIMBUS_NAMESPACE_PREFIX_##NIMaxLogLevel
#endif
#ifndef NIDebugAssertionsShouldBreak
#define NIDebugAssertionsShouldBreak __NIMBUS_NAMESPACE_PREFIX_##NIDebugAssertionsShouldBreak
#endif
#endif
